### PR TITLE
Update 3dsmax.ps1 to enable VRay DR

### PR DESCRIPTION
**Pull request by smith1511**

### CODE REVIEW

**Comment by ascobie** [comment]
Tests are failing with: 

##[section]Starting: Run tests
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/8f4fe805-2c6a-4481-aef9-49a7aec477cb.ps1'
exec : The term 'runnerBatchAccountSecret' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At /home/vsts/work/_temp/8f4fe805-2c6a-4481-aef9-49a7aec477cb.ps1:5 char:1
+ exec { python runner.py "Tests/TestConfigurationWindows.json" "render ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (runnerBatchAccountSecret:String) [Exec], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Exec
 
##[error]PowerShell exited with code '1'.
##[section]Finishing: Run tests

**Comment by davidkydd** [comment]
This is failing because the CI pipeline is set to *not* allow PR's from forks to access secrets. Think we want to keep this behaviour for now, so PR's need to come from main repo not a fork

**Pull request closed without merging**
